# Form implementation generated from reading ui file 'picard-plugin-additional-artists-details/artists_cache_editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_AdditionalArtistsDetailsCacheEditor:
    def setupUi(self, AdditionalArtistsDetailsCacheEditor):
        AdditionalArtistsDetailsCacheEditor.setObjectName("AdditionalArtistsDetailsCacheEditor")
        AdditionalArtistsDetailsCacheEditor.resize(561, 511)
        AdditionalArtistsDetailsCacheEditor.setMinimumSize(QtCore.QSize(500, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(AdditionalArtistsDetailsCacheEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_title = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheEditor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.page_title.setFont(font)
        self.page_title.setObjectName("page_title")
        self.verticalLayout.addWidget(self.page_title)
        self.format_description = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_description.sizePolicy().hasHeightForWidth())
        self.format_description.setSizePolicy(sizePolicy)
        self.format_description.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.format_description.setWordWrap(True)
        self.format_description.setObjectName("format_description")
        self.verticalLayout.addWidget(self.format_description)
        spacerItem = QtWidgets.QSpacerItem(
            20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.verticalLayout.addItem(spacerItem)
        self.artists_list_title = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheEditor)
        font = QtGui.QFont()
        font.setBold(True)
        self.artists_list_title.setFont(font)
        self.artists_list_title.setObjectName("artists_list_title")
        self.verticalLayout.addWidget(self.artists_list_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            4, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.cb_select_all = QtWidgets.QCheckBox(parent=AdditionalArtistsDetailsCacheEditor)
        self.cb_select_all.setText("")
        self.cb_select_all.setTristate(True)
        self.cb_select_all.setObjectName("cb_select_all")
        self.horizontalLayout.addWidget(self.cb_select_all)
        self.checked_count_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheEditor)
        self.checked_count_label.setObjectName("checked_count_label")
        self.horizontalLayout.addWidget(self.checked_count_label)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.filter_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheEditor)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout.addWidget(self.filter_label)
        self.filter_text = QtWidgets.QLineEdit(parent=AdditionalArtistsDetailsCacheEditor)
        self.filter_text.setClearButtonEnabled(True)
        self.filter_text.setObjectName("filter_text")
        self.horizontalLayout.addWidget(self.filter_text)
        self.filter_status_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheEditor)
        self.filter_status_label.setText("")
        self.filter_status_label.setObjectName("filter_status_label")
        self.horizontalLayout.addWidget(self.filter_status_label)
        self.b_filter_previous = QtWidgets.QToolButton(parent=AdditionalArtistsDetailsCacheEditor)
        self.b_filter_previous.setObjectName("b_filter_previous")
        self.horizontalLayout.addWidget(self.b_filter_previous)
        self.b_filter_next = QtWidgets.QToolButton(parent=AdditionalArtistsDetailsCacheEditor)
        self.b_filter_next.setObjectName("b_filter_next")
        self.horizontalLayout.addWidget(self.b_filter_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(parent=AdditionalArtistsDetailsCacheEditor)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidget.setSupportedDragActions(QtCore.Qt.DropAction.IgnoreAction)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem3)
        self.b_remove = QtWidgets.QPushButton(parent=AdditionalArtistsDetailsCacheEditor)
        self.b_remove.setObjectName("b_remove")
        self.horizontalLayout_2.addWidget(self.b_remove)
        self.b_cancel = QtWidgets.QPushButton(parent=AdditionalArtistsDetailsCacheEditor)
        self.b_cancel.setObjectName("b_cancel")
        self.horizontalLayout_2.addWidget(self.b_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AdditionalArtistsDetailsCacheEditor)
        QtCore.QMetaObject.connectSlotsByName(AdditionalArtistsDetailsCacheEditor)
        AdditionalArtistsDetailsCacheEditor.setTabOrder(self.b_cancel, self.cb_select_all)
        AdditionalArtistsDetailsCacheEditor.setTabOrder(self.cb_select_all, self.filter_text)
        AdditionalArtistsDetailsCacheEditor.setTabOrder(self.filter_text, self.b_filter_previous)
        AdditionalArtistsDetailsCacheEditor.setTabOrder(self.b_filter_previous, self.b_filter_next)
        AdditionalArtistsDetailsCacheEditor.setTabOrder(self.b_filter_next, self.b_remove)
        AdditionalArtistsDetailsCacheEditor.setTabOrder(self.b_remove, self.listWidget)

    def retranslateUi(self, AdditionalArtistsDetailsCacheEditor):
        _translate = QtCore.QCoreApplication.translate
        AdditionalArtistsDetailsCacheEditor.setWindowTitle(
            _translate("AdditionalArtistsDetailsCacheEditor", "window.title")
        )
        self.page_title.setText(_translate("AdditionalArtistsDetailsCacheEditor", "page.title"))
        self.format_description.setText(_translate("AdditionalArtistsDetailsCacheEditor", "page.description"))
        self.artists_list_title.setText(_translate("AdditionalArtistsDetailsCacheEditor", "artists_list.title"))
        self.checked_count_label.setText(_translate("AdditionalArtistsDetailsCacheEditor", "(0/0)"))
        self.filter_label.setText(_translate("AdditionalArtistsDetailsCacheEditor", "label.filter"))
        self.filter_text.setToolTip(_translate("AdditionalArtistsDetailsCacheEditor", "tooltip.filter_text"))
        self.filter_text.setPlaceholderText(
            _translate("AdditionalArtistsDetailsCacheEditor", "placeholder.filter_text")
        )
        self.b_filter_previous.setToolTip(_translate("AdditionalArtistsDetailsCacheEditor", "tooltip.filter_previous"))
        self.b_filter_previous.setText(_translate("AdditionalArtistsDetailsCacheEditor", "..."))
        self.b_filter_next.setToolTip(_translate("AdditionalArtistsDetailsCacheEditor", "tooltip.filter_next"))
        self.b_filter_next.setText(_translate("AdditionalArtistsDetailsCacheEditor", "..."))
        self.b_remove.setToolTip(_translate("AdditionalArtistsDetailsCacheEditor", "tooltip.button.remove"))
        self.b_remove.setText(_translate("AdditionalArtistsDetailsCacheEditor", "button.remove"))
        self.b_cancel.setToolTip(_translate("AdditionalArtistsDetailsCacheEditor", "tooltip.button.cancel"))
        self.b_cancel.setText(_translate("AdditionalArtistsDetailsCacheEditor", "button.cancel"))
