# Form implementation generated from reading ui file 'picard-plugin-additional-artists-details/cache_status.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_AdditionalArtistsDetailsCacheStatus:
    def setupUi(self, AdditionalArtistsDetailsCacheStatus):
        AdditionalArtistsDetailsCacheStatus.setObjectName("AdditionalArtistsDetailsCacheStatus")
        AdditionalArtistsDetailsCacheStatus.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        AdditionalArtistsDetailsCacheStatus.resize(500, 250)
        AdditionalArtistsDetailsCacheStatus.setMinimumSize(QtCore.QSize(500, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(AdditionalArtistsDetailsCacheStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_title = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.page_title.setFont(font)
        self.page_title.setObjectName("page_title")
        self.verticalLayout.addWidget(self.page_title)
        self.status_description = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_description.sizePolicy().hasHeightForWidth())
        self.status_description.setSizePolicy(sizePolicy)
        self.status_description.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.status_description.setWordWrap(True)
        self.status_description.setObjectName("status_description")
        self.verticalLayout.addWidget(self.status_description)
        spacerItem = QtWidgets.QSpacerItem(
            20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.artists_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.artists_label.sizePolicy().hasHeightForWidth())
        self.artists_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.artists_label.setFont(font)
        self.artists_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.artists_label.setObjectName("artists_label")
        self.gridLayout.addWidget(self.artists_label, 0, 1, 1, 1)
        self.areas_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areas_label.sizePolicy().hasHeightForWidth())
        self.areas_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.areas_label.setFont(font)
        self.areas_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.areas_label.setObjectName("areas_label")
        self.gridLayout.addWidget(self.areas_label, 0, 2, 1, 1)
        self.session_cache_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.session_cache_label.sizePolicy().hasHeightForWidth())
        self.session_cache_label.setSizePolicy(sizePolicy)
        self.session_cache_label.setObjectName("session_cache_label")
        self.gridLayout.addWidget(self.session_cache_label, 1, 0, 1, 1)
        self.cache_database_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        self.cache_database_label.setObjectName("cache_database_label")
        self.gridLayout.addWidget(self.cache_database_label, 2, 0, 1, 1)
        self.session_artists_count = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        self.session_artists_count.setText("0")
        self.session_artists_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.session_artists_count.setObjectName("session_artists_count")
        self.gridLayout.addWidget(self.session_artists_count, 1, 1, 1, 1)
        self.session_areas_count = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        self.session_areas_count.setText("0")
        self.session_areas_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.session_areas_count.setObjectName("session_areas_count")
        self.gridLayout.addWidget(self.session_areas_count, 1, 2, 1, 1)
        self.database_artists_count = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        self.database_artists_count.setText("0")
        self.database_artists_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.database_artists_count.setObjectName("database_artists_count")
        self.gridLayout.addWidget(self.database_artists_count, 2, 1, 1, 1)
        self.database_areas_count = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        self.database_areas_count.setText("0")
        self.database_areas_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.database_areas_count.setObjectName("database_areas_count")
        self.gridLayout.addWidget(self.database_areas_count, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.verticalLayout.addItem(spacerItem2)
        self.status_note_label = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        font = QtGui.QFont()
        font.setBold(True)
        self.status_note_label.setFont(font)
        self.status_note_label.setObjectName("status_note_label")
        self.verticalLayout.addWidget(self.status_note_label)
        self.status_note = QtWidgets.QLabel(parent=AdditionalArtistsDetailsCacheStatus)
        self.status_note.setText("")
        self.status_note.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.status_note.setWordWrap(True)
        self.status_note.setObjectName("status_note")
        self.verticalLayout.addWidget(self.status_note)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.verticalLayout.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AdditionalArtistsDetailsCacheStatus)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AdditionalArtistsDetailsCacheStatus)
        QtCore.QMetaObject.connectSlotsByName(AdditionalArtistsDetailsCacheStatus)

    def retranslateUi(self, AdditionalArtistsDetailsCacheStatus):
        _translate = QtCore.QCoreApplication.translate
        AdditionalArtistsDetailsCacheStatus.setWindowTitle(
            _translate("AdditionalArtistsDetailsCacheStatus", "window.title")
        )
        self.page_title.setText(_translate("AdditionalArtistsDetailsCacheStatus", "page.title"))
        self.status_description.setText(_translate("AdditionalArtistsDetailsCacheStatus", "page.description"))
        self.artists_label.setText(_translate("AdditionalArtistsDetailsCacheStatus", "label.artists"))
        self.areas_label.setText(_translate("AdditionalArtistsDetailsCacheStatus", "label.areas"))
        self.session_cache_label.setText(_translate("AdditionalArtistsDetailsCacheStatus", "label.session_cache"))
        self.cache_database_label.setText(_translate("AdditionalArtistsDetailsCacheStatus", "label.cache_database"))
        self.status_note_label.setText(_translate("AdditionalArtistsDetailsCacheStatus", "label.status_notes"))
